[tracing]
format = "pretty" # Values: pretty, json
level = "debug" # Values: DEBUG,ERROR,INFO,WARN,TRACE,OFF

off = [
    "tokio",
    "hyper",
    "axum",
] 
debug = ["rtm-auth"] 
error = ["rtm-auth"]
info = ["rtm-auth"]  
warn = ["rtm-auth"]
trace = ["rtm-auth"]


[db]
db_uri = "postgres://demo_user:demo_pass@localhost/auth"
pool_size = 35
run_migrations = true

[server]
debug = true

jwt_secret_key = "veryverysercretkey"
jwt_schema_key = "Bearer"
jwt_token_exp = 1800 
