[package]
name = "rtm-auth"
version = "0.1.0"
edition = "2021"
authors = ["Daniil Trotsenko <daniil.trotsenko.dev@gmail.com>"]

[dependencies]
axum = "0.7.4"
tokio = { version = "1.0", features = ["full"]}

serde = { version = "1.0", features = ["derive"] }
serde_json = "1"

async-trait = "0.1"
anyhow = "1.0"
