[package]
name = "rtm-auth"
version = "0.1.0"
edition = "2021"
authors=["Daniil Trotsenko daniil.trotsenko.dev@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]] # Bin to run actix-web API
name = "api"
path = "src/main.rs"


[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
futures = "0.3"
