---
version: '3.8'
services:
    rtm_auth_db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=rtm_auth
            - POSTGRES_PASSWORD=rtm_auth
            - POSTGRES_DB=auth
        ports:
            - 5432:5432
        volumes:
            - rtm_auth_db:/var/postgresql/data
volumes:
    rtm_auth_db:
        driver: local
